
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 06 14:35:22 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 33;
  public static final int LBRACKET = 26;
  public static final int EQUALITY = 28;
  public static final int MULT = 42;
  public static final int CHAR = 47;
  public static final int CONST = 9;
  public static final int ASSIGNMENT = 35;
  public static final int LPAREN = 22;
  public static final int SEMI = 18;
  public static final int CONTINUE = 15;
  public static final int MINUS = 41;
  public static final int RPAREN = 23;
  public static final int AND = 36;
  public static final int LT = 32;
  public static final int OR = 37;
  public static final int IN = 34;
  public static final int BOOL = 48;
  public static final int COMMA = 20;
  public static final int CLASS = 7;
  public static final int INC = 38;
  public static final int DIV = 43;
  public static final int PLUS = 40;
  public static final int IF = 49;
  public static final int THIS = 16;
  public static final int DOT = 21;
  public static final int INEQUALITY = 29;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int RBRACKET = 27;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int NUMBER = 45;
  public static final int MOD = 44;
  public static final int IDENT = 46;
  public static final int BREAK = 6;
  public static final int VOID = 5;
  public static final int GTE = 31;
  public static final int FOREACH = 17;
  public static final int COLON = 19;
  public static final int ELSE = 50;
  public static final int LBRACE = 24;
  public static final int ENUM = 8;
  public static final int READ = 13;
  public static final int WHILE = 11;
  public static final int RBRACE = 25;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int DEC = 39;
  public static final int GT = 30;
  public static final int PRINT = 3;
  public static final int DO = 10;
}

